apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: reservation-service
build:
  artifacts:
    - image: reservation-service
      jib:
        project: com.ubluetech:reservation-service
manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/service.yaml
