package com.ubluetech.reservationservice.domain;

enum EventType {
    RESERVATION_REQUESTED_EVENT,
    AVAILABILITY_CONFIRMED,
    RESERVATION_CREATED_EVENT,
    RESERVATION_CANCELED_EVENT,
    RESERVATION_MODIFIED_EVENT,
    RESERVATION_CHECKEDIN_EVENT,
    RESERVATION_CHECKEDOUT_EVENT,
    RESERVATION_CONFIRMATION_SENT_EVENT,
    PAYMENT_AUTHORIZED_EVENT,
    PAYMENT_COMPLETED_EVENT,
    PAYMENT_FAILED_EVENT
}
