apiVersion: v1
kind: Service
metadata:
  name: reservation-service-kuservice
spec:
  type: LoadBalancer
  selector:
    app: reservation-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      