apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-service-deployment
  namespace: reservation-develop
  labels:
    app: reservation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation-service
  template:
    metadata:
      labels:
        app: reservation-service
    spec:
      automountServiceAccountToken: false
      containers:
      - name: reservation-service
        image: reservation-service:v0.1.0-alpha
        volumeMounts:
          - name: config-volume
            mountPath: /workspace/config
        imagePullPolicy: Never # SHOULD NOT DO IT ON PRODUCTION the kubelet does not try fetching the image. If the image is somehow already present locally
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
      
        # readinessProbe:
        #   httpGet:
        #     port: 8080
        #     path: /actuator/health/readiness

        # livenessProbe:
        #   httpGet:
        #     port: 8080
        #     path: /actuator/health/liveness

        # lifecycle:
        #   preStop:
        #     exec:
        #       command: ["sh", "-c", "sleep 10"]

      volumes:
      - name: config-volume
        configMap:
          name: reservation-service-config
          