apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:	
- namespace.yaml
- kafka-local.yaml
- service.yaml
- deployment.yaml

configMapGenerator:
  - name: reservation-service-config
    namespace: reservation-develop
    files:
      - application.yaml