name: Java CI (Reservation Service Merge Request)
on:
  pull_request:
    types: [closed]

jobs:
  verify-reservation-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build and Verify with Maven
      run: ./mvnw verify
